### ISSUE TITLE
Consider adding LICENSE file

### ISSUE THREAD

**Issue by rfairley** [arcnmx/pipe-rs#6]
Consider adding a license file to this repo, for example of the form given at: https://opensource.org/licenses/MIT.

Reason for this request: I would like to package the `pipe` crate in Fedora, which is utilized by the latest version of the `coreos-installer` crate (an installer program for Fedora CoreOS).

Would be much appreciated to have the license file included, so that the file including the license and copyright could be distributed as part of the RPM package in Fedora.

**Comment by dustymabe** [comment]
You could achieve this by adding a symlink:

```
ln -s ./COPYING ./LICENSE
```

**Comment by rfairley** [comment]
Ah, yes symlink would be fine. Did not see the COPYING file before. Will add the symlink downstream - that resolves the issue I had.
